//! Pfam equivalence tests — compare Rust hmmsearch against C HMMER golden files.
//!
//! These tests download 18 diverse Pfam HMMs and search them against 20k human
//! Swiss-Prot proteins. Golden reference files were generated by C HMMER 3.4.
//!
//! Tests verify:
//! - Hit set overlap (same targets found)
//! - Score agreement (bit scores within tolerance)
//! - Ranking consistency (same top hits)
//! - No false negatives for strong hits (E < 1e-10)
//!
//! NOTE: These tests require test_data/ and tests/golden/pfam_*.tblout files,
//! which are generated by running C hmmsearch on downloaded Pfam HMMs.

use std::collections::{HashMap, HashSet};
use std::process::Command;

fn binary_path() -> std::path::PathBuf {
    let mut path = std::env::current_exe()
        .unwrap()
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf();
    path.push("hmmer");
    path
}

fn test_path(relative: &str) -> String {
    format!("{}/{}", env!("CARGO_MANIFEST_DIR"), relative)
}

/// Parse tblout into map of (target, query) -> (evalue, score).
fn parse_tblout_map(content: &str) -> HashMap<(String, String), (f64, f64)> {
    let mut map = HashMap::new();
    for line in content.lines() {
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split_whitespace().collect();
        if f.len() < 6 {
            continue;
        }
        let ev: f64 = f[4].parse().unwrap_or(f64::INFINITY);
        let sc: f64 = f[5].parse().unwrap_or(0.0);
        map.insert((f[0].to_string(), f[2].to_string()), (ev, sc));
    }
    map
}

/// Parse tblout into Vec of (target, query, evalue, score).
fn parse_tblout_vec(content: &str) -> Vec<(String, String, f64, f64)> {
    content
        .lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .filter_map(|line| {
            let f: Vec<&str> = line.split_whitespace().collect();
            if f.len() < 6 {
                return None;
            }
            let ev: f64 = f[4].parse().ok()?;
            let sc: f64 = f[5].parse().ok()?;
            Some((f[0].to_string(), f[2].to_string(), ev, sc))
        })
        .collect()
}

/// Run Rust hmmsearch and return tblout content.
fn rust_search(hmm: &str, seqdb: &str) -> String {
    let dir = tempfile::tempdir().unwrap();
    let tblout = dir.path().join("tblout.txt");
    let output = Command::new(binary_path())
        .args(&[
            "search",
            "--noali",
            "--tblout",
            tblout.to_str().unwrap(),
            hmm,
            seqdb,
        ])
        .output()
        .expect("failed to run hmmer search");
    assert!(
        output.status.success(),
        "search failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    std::fs::read_to_string(&tblout).unwrap_or_default()
}

/// Compare Rust results against C golden file.
struct ComparisonResult {
    c_count: usize,
    r_count: usize,
    common: usize,
    c_only: usize,
    r_only: usize,
    overlap_pct: f64,
    /// Strong hits (E<1e-10 in C) missed by Rust
    strong_missed: Vec<String>,
    /// Max bit score diff for common strong hits
    max_score_diff: f64,
}

fn compare_results(golden_path: &str, hmm: &str, seqdb: &str) -> ComparisonResult {
    let c_content = std::fs::read_to_string(golden_path)
        .unwrap_or_else(|e| panic!("Cannot read golden file {}: {}", golden_path, e));
    let c_map = parse_tblout_map(&c_content);
    let r_tbl = rust_search(hmm, seqdb);
    let r_vec = parse_tblout_vec(&r_tbl);
    let r_map = parse_tblout_map(&r_tbl);

    let c_keys: HashSet<(String, String)> = c_map.keys().cloned().collect();
    let r_keys: HashSet<(String, String)> = r_map.keys().cloned().collect();
    let common = c_keys.intersection(&r_keys).count();
    let c_only = c_keys.difference(&r_keys).count();
    let r_only = r_keys.difference(&c_keys).count();
    let total = c_keys.union(&r_keys).count();
    let overlap = if total > 0 {
        common as f64 / total as f64 * 100.0
    } else {
        100.0
    };

    // Find strong C hits missed by Rust
    let mut strong_missed = Vec::new();
    for (key, &(ev, _sc)) in &c_map {
        if ev < 1e-10 && !r_keys.contains(key) {
            strong_missed.push(format!("{}:{} E={:.2e}", key.0, key.1, ev));
        }
    }

    // Max score diff for common strong hits
    let mut max_score_diff = 0.0_f64;
    for (target, query, _r_ev, r_sc) in &r_vec {
        let key = (target.clone(), query.clone());
        if let Some(&(c_ev, c_sc)) = c_map.get(&key) {
            if c_ev < 1e-10 && c_sc > 20.0 {
                let diff = (r_sc - c_sc).abs();
                max_score_diff = max_score_diff.max(diff);
            }
        }
    }

    ComparisonResult {
        c_count: c_keys.len(),
        r_count: r_keys.len(),
        common,
        c_only,
        r_only,
        overlap_pct: overlap,
        strong_missed,
        max_score_diff,
    }
}

// Shared test database
// Prefer uncompressed for speed; fall back to .gz (which is committed to git)
fn seqdb_path() -> String {
    let uncompressed = format!(
        "{}/test_data/human_swissprot_2k.fasta",
        env!("CARGO_MANIFEST_DIR")
    );
    if std::path::Path::new(&uncompressed).exists() {
        return "test_data/human_swissprot_2k.fasta".to_string();
    }
    // Decompress .gz on first use
    let gz = format!(
        "{}/test_data/human_swissprot_2k.fasta.gz",
        env!("CARGO_MANIFEST_DIR")
    );
    if std::path::Path::new(&gz).exists() {
        use std::io::Read;
        let f = std::fs::File::open(&gz).unwrap();
        let mut decoder = flate2::read::GzDecoder::new(f);
        let mut data = Vec::new();
        decoder.read_to_end(&mut data).unwrap();
        std::fs::write(&uncompressed, &data).unwrap();
        return "test_data/human_swissprot_2k.fasta".to_string();
    }
    "test_data/human_swissprot_2k.fasta.gz".to_string()
}

const SEQDB_GZ: &str = "test_data/human_swissprot_2k.fasta.gz";

// ============================================================
// Per-family equivalence tests
// ============================================================

macro_rules! pfam_test {
    ($test_name:ident, $family:expr, $min_overlap:expr, $max_strong_missed:expr, $max_score_diff:expr) => {
        #[test]
        fn $test_name() {
            let golden = test_path(&format!("tests/golden/pfam_{}.tblout", $family));
            let hmm = test_path(&format!("test_data/{}_pfam.hmm", $family));
            let seqdb = test_path(&seqdb_path());

            // Skip if golden file or HMM doesn't exist
            if !std::path::Path::new(&golden).exists() {
                eprintln!("SKIP: golden file not found: {}", golden);
                return;
            }
            if !std::path::Path::new(&hmm).exists() {
                eprintln!("SKIP: HMM not found: {}", hmm);
                return;
            }

            let r = compare_results(&golden, &hmm, &seqdb);

            // Check overlap percentage
            assert!(r.overlap_pct >= $min_overlap,
                "{}: hit overlap {:.1}% below minimum {:.0}% (C={} Rust={} common={} C-only={} R-only={})",
                $family, r.overlap_pct, $min_overlap,
                r.c_count, r.r_count, r.common, r.c_only, r.r_only);

            // Check no strong hits missed
            assert!(r.strong_missed.len() <= $max_strong_missed,
                "{}: {} strong hits (E<1e-10) missed by Rust (max allowed: {}): {:?}",
                $family, r.strong_missed.len(), $max_strong_missed,
                &r.strong_missed[..r.strong_missed.len().min(10)]);

            // Check score accuracy for common strong hits (skip for repeat domains)
            if $max_score_diff > 0.0 {
                assert!(r.max_score_diff <= $max_score_diff,
                    "{}: max score diff {:.1} bits exceeds tolerance {:.0} bits",
                    $family, r.max_score_diff, $max_score_diff);
            }
        }
    };
}

// Single-domain families: high overlap, tight score tolerance
//                          test name                    family          min_ovl  max_miss  max_sc_diff
pfam_test!(test_pfam_globin, "Globin", 85.0, 0, 15.0);
pfam_test!(test_pfam_trypsin, "Trypsin", 95.0, 0, 15.0);
pfam_test!(test_pfam_ras, "Ras", 90.0, 0, 15.0);
pfam_test!(test_pfam_gtp_eftu, "GTP_EFTU", 85.0, 0, 15.0);
pfam_test!(test_pfam_rvt_1, "RVT_1", 95.0, 0, 15.0);
pfam_test!(test_pfam_adh_short, "adh_short", 75.0, 0, 15.0);

// Multi-domain families: good overlap, wider score tolerance
// (multi-domain proteins like TITIN accumulate score differences across domains)
pfam_test!(test_pfam_pkinase, "Pkinase", 95.0, 1, 60.0);
pfam_test!(test_pfam_pkinase_tyr, "Pkinase_Tyr", 95.0, 1, 55.0);
pfam_test!(test_pfam_rrm_1, "RRM_1", 90.0, 0, 25.0);
pfam_test!(test_pfam_homeodomain, "Homeodomain", 85.0, 0, 25.0);
pfam_test!(test_pfam_aaa, "AAA", 70.0, 0, 20.0);

// GPCR / transmembrane: relaxed overlap, wider score tolerance (bias filter sensitive)
pfam_test!(test_pfam_7tm_1, "7tm_1", 85.0, 5, 40.0);

// ABC transporter: Rust finds more hits (relaxed overlap)
pfam_test!(test_pfam_abc_tran, "ABC_tran", 55.0, 0, 20.0);

// Sugar transporter: large divergence in hit count (known issue, bias filter sensitive)
pfam_test!(test_pfam_sugar_tr, "Sugar_tr", 25.0, 0, 40.0);

// Repeat domain families: score divergence expected (domain accumulation)
// Use max_score_diff = 0.0 to skip score check for repeats
pfam_test!(test_pfam_ank, "Ank", 95.0, 0, 0.0);
pfam_test!(test_pfam_wd40, "WD40", 90.0, 0, 0.0);
pfam_test!(test_pfam_ig, "ig", 85.0, 5, 0.0);
pfam_test!(test_pfam_zf_c2h2, "zf_C2H2", 80.0, 5, 0.0);

// ============================================================
// Cross-cutting tests
// ============================================================

/// Verify that no family has Rust completely failing (0 hits when C finds many).
#[test]
fn test_no_total_failures() {
    let families = [
        "Globin",
        "Trypsin",
        "Ras",
        "GTP_EFTU",
        "Pkinase",
        "RRM_1",
        "AAA",
        "7tm_1",
        "ABC_tran",
        "Ank",
        "WD40",
        "ig",
        "zf_C2H2",
        "Homeodomain",
        "Pkinase_Tyr",
        "RVT_1",
        "adh_short",
        "Sugar_tr",
    ];

    for family in &families {
        let golden = test_path(&format!("tests/golden/pfam_{}.tblout", family));
        let hmm = test_path(&format!("test_data/{}_pfam.hmm", family));
        let seqdb = test_path(&seqdb_path());

        if !std::path::Path::new(&golden).exists() || !std::path::Path::new(&hmm).exists() {
            continue;
        }

        let c_content = std::fs::read_to_string(&golden).unwrap();
        let c_count = c_content
            .lines()
            .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
            .count();

        if c_count > 10 {
            let r_tbl = rust_search(&hmm, &seqdb);
            let r_count = r_tbl
                .lines()
                .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
                .count();
            assert!(
                r_count > 0,
                "{}: C finds {} hits but Rust finds 0!",
                family,
                c_count
            );
            assert!(
                r_count as f64 >= c_count as f64 * 0.25,
                "{}: Rust finds {} hits vs C's {} — less than 25%",
                family,
                r_count,
                c_count
            );
        }
    }
}

/// Verify that for single-domain families, the #1 hit (by score) is the same in C and Rust.
/// Excludes transmembrane/bias-sensitive families where ordering can diverge.
#[test]
fn test_top_hit_agreement() {
    let families = [
        "Globin",
        "Trypsin",
        "Ras",
        "GTP_EFTU",
        "Pkinase",
        "RRM_1",
        "AAA",
        "Pkinase_Tyr",
        "RVT_1",
        "adh_short",
    ];

    for family in &families {
        let golden = test_path(&format!("tests/golden/pfam_{}.tblout", family));
        let hmm = test_path(&format!("test_data/{}_pfam.hmm", family));
        let seqdb = test_path(&seqdb_path());

        if !std::path::Path::new(&golden).exists() || !std::path::Path::new(&hmm).exists() {
            continue;
        }

        let c_content = std::fs::read_to_string(&golden).unwrap();
        let c_hits = parse_tblout_vec(&c_content);
        let r_tbl = rust_search(&hmm, &seqdb);
        let r_hits = parse_tblout_vec(&r_tbl);

        if c_hits.is_empty() || r_hits.is_empty() {
            continue;
        }

        // Top hit target should match (same protein found as #1)
        // For multi-query HMMs, check per query
        let c_top = &c_hits[0].0;
        let _r_top = &r_hits[0].0;

        // Check if C's top hit is in Rust's top 3
        let r_top3: HashSet<&str> = r_hits.iter().take(3).map(|h| h.0.as_str()).collect();
        assert!(
            r_top3.contains(c_top.as_str()),
            "{}: C top hit '{}' not in Rust top 3 {:?}",
            family,
            c_top,
            r_top3
        );
    }
}

/// Check that strong C hits (E < 1e-20) are nearly all found by Rust.
#[test]
fn test_strong_hit_recall() {
    let families = [
        "Globin",
        "Trypsin",
        "Ras",
        "GTP_EFTU",
        "Pkinase",
        "RRM_1",
        "AAA",
        "7tm_1",
        "ABC_tran",
        "Ank",
        "WD40",
        "ig",
        "zf_C2H2",
        "Homeodomain",
        "Pkinase_Tyr",
        "RVT_1",
        "adh_short",
        "Sugar_tr",
    ];

    let mut total_strong = 0;
    let mut total_missed = 0;

    for family in &families {
        let golden = test_path(&format!("tests/golden/pfam_{}.tblout", family));
        let hmm = test_path(&format!("test_data/{}_pfam.hmm", family));
        let seqdb = test_path(&seqdb_path());

        if !std::path::Path::new(&golden).exists() || !std::path::Path::new(&hmm).exists() {
            continue;
        }

        let c_content = std::fs::read_to_string(&golden).unwrap();
        let c_map = parse_tblout_map(&c_content);
        let r_tbl = rust_search(&hmm, &seqdb);
        let r_map = parse_tblout_map(&r_tbl);

        let r_keys: HashSet<(String, String)> = r_map.keys().cloned().collect();

        for (key, &(ev, _sc)) in &c_map {
            if ev < 1e-20 {
                total_strong += 1;
                if !r_keys.contains(key) {
                    total_missed += 1;
                }
            }
        }
    }

    let recall = if total_strong > 0 {
        (total_strong - total_missed) as f64 / total_strong as f64 * 100.0
    } else {
        100.0
    };

    assert!(
        recall >= 95.0,
        "Strong hit recall: {:.1}% ({} missed of {} total) — should be >= 95%",
        recall,
        total_missed,
        total_strong
    );
}

/// Verify tblout output format is correct across all families.
#[test]
fn test_tblout_format_all_families() {
    let families = ["Globin", "Pkinase", "RRM_1", "7tm_1", "Ank"];

    for family in &families {
        let hmm = test_path(&format!("test_data/{}_pfam.hmm", family));
        let seqdb = test_path(&seqdb_path());

        if !std::path::Path::new(&hmm).exists() {
            continue;
        }

        let tbl = rust_search(&hmm, &seqdb);

        for (i, line) in tbl.lines().enumerate() {
            if line.starts_with('#') || line.trim().is_empty() {
                continue;
            }
            let fields: Vec<&str> = line.split_whitespace().collect();
            assert!(
                fields.len() >= 18,
                "{} line {}: expected >=18 fields, got {}: {}",
                family,
                i + 1,
                fields.len(),
                &line[..line.len().min(100)]
            );

            // Verify E-value is parseable
            let ev: Result<f64, _> = fields[4].parse();
            assert!(
                ev.is_ok(),
                "{} line {}: E-value '{}' not parseable",
                family,
                i + 1,
                fields[4]
            );

            // Verify score is parseable
            let sc: Result<f64, _> = fields[5].parse();
            assert!(
                sc.is_ok(),
                "{} line {}: score '{}' not parseable",
                family,
                i + 1,
                fields[5]
            );

            // Name should not contain accession dash
            assert!(
                fields[0] != "-",
                "{} line {}: target name is '-'",
                family,
                i + 1
            );
        }
    }
}
